SchoolManagementSystemP8/Controllers/CourseController.cs
using SchoolManagementSystemP8.ADONET;
using SchoolManagementSystemP8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystemP8.Controllers
{
    public class CourseController : Controller
    {
        SMSEntities db = new SMSEntities();
        // GET: Course
        public ActionResult Index()
        {
            List<CourseVM> list = new List<CourseVM>();
            var data = db.CourseDetails.ToList();
            foreach (var item in data)
            {
                CourseVM obj = new CourseVM()
                {
                    CourseId=item.CourseId,
                    CourseName=item.CourseName,
                    CreatedBy=item.CreatedBy,
                    CreatedDate=item.CreatedDate,
                    CreditHours=item.CreditHours,
                    Faculty=item.Faculty,
                    Status=item.Status
                };
                list.Add(obj);
            }
            return View(list);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost] 
        public ActionResult Create(CourseVM model)
        {
            CourseDetail data = new CourseDetail()
            {
                 CourseId=model.CourseId,
                 CourseName=model.CourseName,
                 //CreatedBy=User.Identity.
                 CreatedDate=DateTime.Now,
                 CreditHours=model.CreditHours,
                 Faculty=model.Faculty,
                 Status=model.Status,
            };
            db.CourseDetails.Add(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var model=db.CourseDetails.Find(id);
            CourseVM data = new CourseVM()
            {
                CourseId = model.CourseId,
                CourseName = model.CourseName,
                //CreatedBy=User.Identity.
                CreatedDate = DateTime.Now,
                CreditHours = model.CreditHours,
                Faculty = model.Faculty,
                Status = model.Status,
            };
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(CourseVM obj)
        {
            var olddata = db.CourseDetails.Find(obj.CourseId);
            olddata.CourseName = obj.CourseName;
            olddata.CreditHours = obj.CreditHours;
            olddata.Status = obj.Status;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var data = db.CourseDetails.Find(id);
            db.CourseDetails.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

SchoolManagementSystemP8/Controllers/DistrictController.cs
using SchoolManagementSystemP8.ADONET;
using SchoolManagementSystemP8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystemP8.Controllers
{
    public class DistrictController : Controller
    {
        SMSEntities db = new SMSEntities();
        // GET: List District
        public ActionResult Index()
        {
            List<DistrictVM> list = new List<DistrictVM>();
            var data = db.TBL_District.ToList();
            foreach (var item in data)
            {
                DistrictVM model = new DistrictVM();
                model.ProvinceId = item.ProvinceId;
                model.ProvinceName = item.TBL_Province.ProvinceName;
                model.DistrictId = item.DistrictId;
                model.DistrictName = item.DistrictName;
                model.Status = item.Status??false;
                list.Add(model);
            }
            return View(list);
        }
        //Create District 
        public ActionResult Create()
        {
            return View();
        }
        //Post data
        [HttpPost]
        public ActionResult Create(DistrictVM obj)
        {
            TBL_District model = new TBL_District();
            model.DistrictId = obj.DistrictId;
            model.DistrictName = obj.DistrictName;
            model.ProvinceId = obj.ProvinceId;
            model.Status = obj.Status;
            //Add to entities
            db.TBL_District.Add(model);
            //publish changes
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Edit district
        public ActionResult Edit(int Id)
        {
            TBL_District model = db.TBL_District.Find(Id);
            DistrictVM obj = new DistrictVM();
            obj.DistrictId = model.DistrictId;
            obj.DistrictName = model.DistrictName;
            obj.ProvinceId = model.ProvinceId;
            obj.Status = model.Status??false;
            return View(obj);
        }
        //Post data
        [HttpPost]
        public ActionResult Edit(DistrictVM obj)
        {
            TBL_District model = db.TBL_District.Find(obj.DistrictId);
            model.DistrictName = obj.DistrictName;
            model.ProvinceId = obj.ProvinceId;
            model.Status = obj.Status;
            //Add to entities
           // db.TBL_District.Add(model);
            //publish changes
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int Id)
        {
            TBL_District obj = db.TBL_District.Find(Id);
            db.TBL_District.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SchoolManagementSystemP8/Controllers/ProvinceController.cs
using SchoolManagementSystemP8.ADONET;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystemP8.Controllers
{
    public class ProvinceController : Controller
    {
        SMSEntities db = new SMSEntities();
        // GET: Province
        //1:List all the Province
        public ActionResult Index()
        {
            List<TBL_Province> obj = db.TBL_Province.ToList();
            return View(obj);
        }

        //2: Create Province Render Form
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        //3: Post Province Data
        [HttpPost]
        public ActionResult Create(TBL_Province model)
        {
            db.TBL_Province.Add(model);
            var result=db.SaveChanges();
            return View();
        }
        //Edit Method
        public ActionResult Edit(int Id=1)
        {
            TBL_Province obj = db.TBL_Province.Find(Id);
            return View(obj);
        }
        //Edit POSt
        [HttpPost]
        public ActionResult Edit(TBL_Province model)
        {
            TBL_Province obj = db.TBL_Province.Find(model.ProvinceId);
            obj.ProvinceName = model.ProvinceName;
            obj.Status = model.Status;
            var result = db.SaveChanges();
            return View();
        }
        public ActionResult Delete(int Id)
        {
            try
            {
                TBL_Province obj = db.TBL_Province.Find(Id);
                if (obj != null)
                {
                    db.TBL_Province.Remove(obj);
                }
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");

        }
    }
}

SchoolManagementSystemP8/Controllers/StudentInfoController.cs
using SchoolManagementSystemP8.ADONET;
using SchoolManagementSystemP8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystemP8.Controllers
{
    public class StudentInfoController : Controller
    {
        SMSEntities db = new SMSEntities();
        // GET: StudentInfo
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<ParentDetailsVM> list = new List<ParentDetailsVM>();
            StudentInfoVM model = new StudentInfoVM();
            List<TBL_Relationship> rel = new List<TBL_Relationship>();
            rel = db.TBL_Relationship.ToList();
            model.RelationshipList = rel;
            var parentList = db.TBL_Relationship.ToList();
            foreach (var item in parentList)
            {
                ParentDetailsVM parent = new ParentDetailsVM();
                parent.Relationship = item.RelationshipId;
                list.Add(parent);
            }
            model.ParentList = list;

            List<TBL_EducationInfo> edulist = new List<TBL_EducationInfo>();
            var educationlist = db.StudentLevels.ToList();
            foreach (var item in educationlist)
            {
                TBL_EducationInfo model1 = new TBL_EducationInfo();
                model1.Id = item.Id;
                edulist.Add(model1);
            }
            model.EducationList = edulist;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(StudentInfoVM model)
        {
            TBL_Student stu = new TBL_Student()
            {
                FirstName=model.FirstName,
                LastName=model.LastName,
                DOB=model.DOB,
                CDistrictId=model.CDistrictId,
                CMunicipalityID=model.CMunicipalityID,
                CProvinceId=model.CProvinceId,
                CreatedDate=DateTime.Now,
                Email=model.Email,
                Gender=model.Gender,
                PDistrictID=model.PDistrictID,
                PProvinceId=model.PProvinceId,
                PWardNo=model.PWardNo,
                Phone=model.Phone,
                PMunicipalityID=model.PMunicipalityID,
            };
            db.TBL_Student.Add(stu);
            foreach (var item in model.ParentList)
            {
                TBL_ParentDetails parent = new TBL_ParentDetails()
                {
                    StudentId= stu.Id,
                    Relationship = item.Relationship,
                    ParentPhone=item.ParentPhone,
                    ParentName=item.ParentPhone,
                    Address=item.Address,
                };
                db.TBL_ParentDetails.Add(parent);
            }
            foreach (var item in model.EducationList)
            {
                TBL_EducationInfo edu = new TBL_EducationInfo()
                {
                    StudentId = stu.Id,
                    Board = item.Board,
                    College = item.College,
                    Grade = item.Grade,
                    Status = true,
                    PassedYear = item.PassedYear,
                    CreatedDate = DateTime.Now,
                };
            }
            db.SaveChanges();
            return View(model);
        }
    }
}

SchoolManagementSystemP8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>School Management System</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- DataTables CSS -->
    <link href="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">School Management System</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li class="divider"></li>
                        <li>
                            @Html.ActionLink("Logout","Logout","Account")
                            @*<a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>*@
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        @*<li>

                            <a ><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>*@
                        <li>
                            @Html.ActionLink("Dashboard", "Index", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("User Registration", "Register", "Account")
                        </li>
                        <li>
                            @*<a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Configuration<span class="fa arrow"></span></a>*@
                            <ul class="nav nav-second-level">
                                <li>
                                    @Html.ActionLink("Province Setup","Index","Province")
                                </li>

                                <li>
                                    @Html.ActionLink("District Setup", "Index", "District")
                                </li>

                                <li>
                                    @Html.ActionLink("Muncipality Setup", "Index", "Municipality")
                                </li>

                                <li>
                                    @Html.ActionLink("Course Setup", "Index", "Course")
                                </li>
                                <li>
                                    @Html.ActionLink("Parent Relationship Setup", "Index", "Relationship")
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            @Html.ActionLink("Add Student", "Create", "StudentInfo")
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/sb-admin-2.js"></script>
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
</body>
</html>