SchoolManagementSystemP8/Controllers/RelationshipController.cs
using SchoolManagementSystemP8.ADONET;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystemP8.Controllers
{
    public class RelationshipController : Controller
    {
        // GET: Relationship
        SMSEntities db = new SMSEntities();
        public ActionResult Index()
        {
            return View(db.TBL_Relationship.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TBL_Relationship model)
        {
            db.TBL_Relationship.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int Id)
        {
            return View(db.TBL_Relationship.Find(Id));
        }
        [HttpPost]
        public ActionResult Edit(TBL_Relationship model)
        {
            var data = db.TBL_Relationship.Find(model.RelationshipId);
            data.RelationshipName = model.RelationshipName;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var data = db.TBL_Relationship.Find(id);
            db.TBL_Relationship.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SchoolManagementSystemP8/Views/Relationship/Create.cshtml
@model SchoolManagementSystemP8.ADONET.TBL_Relationship
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm())
{ 
<div class="container">
    <div class="form-group">
        <label class="col-md-2">Relationship Name</label>
        @Html.TextBoxFor(m => m.RelationshipName, new { @class = "form-control", id = "provinceName" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-default" value="Submit Form" />
    </div>
</div>
}

SchoolManagementSystemP8/Views/Relationship/Edit.cshtml
@model SchoolManagementSystemP8.ADONET.TBL_Relationship
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(x=>x.RelationshipId)
    <div class="container">
        <div class="form-group">
            <label class="col-md-2">Relationship Name</label>
            @Html.TextBoxFor(m => m.RelationshipName, new { @class = "form-control", id = "provinceName" })
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-default" value="Submit Form" />
        </div>
    </div>
}

SchoolManagementSystemP8/Views/Relationship/Index.cshtml
@model List<SchoolManagementSystemP8.ADONET.TBL_Relationship>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.ActionLink("Create New", "Create", "Relationship")
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
               Parent Relationship
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>
                                    Relationship Name
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
            {
                                <tr>
                                    <td>
                                        @item.RelationshipName
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.RelationshipId }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.RelationshipId })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>